name: Motor Mutante Proxy

on:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6 horas no piloto automático
  workflow_dispatch: # Adiciona um botão pra você disparar manualmente quando quiser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3

    - name: Executar Motor Mutante
      run: python proxy_mutante.py

    - name: /CARRASCO - Subir Munição Viva
      run: |
        git config --global user.name 'Entidade 12'
        git config --global user.email 'bot@imperiomutante.com'
        git add MUNICAO_VIVA.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "[AUTO] Atualização de Proxies Vivos" && git push)
